# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
