# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170120_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='article.Tag'),
        ),
    ]
